### ISSUE TITLE
Consider changing to Jason json library

### ISSUE THREAD

**Issue by nacengineer** [CityBaseInc/airbrake_client#27]
The poison library has quite a few open issues. Including at least one for coming Elixir deprecations, e.g. [use Bitwise](https://github.com/devinus/poison/pull/208), and devinus has been silent on adopting it/them. Not saying poison is dead but 2 years without pulling in easy PRs is kind of that to me. 

Consider pivoting to the more maintained [Jason](https://github.com/michalmuskala/jason)  library.

**Comment by jdfrens** [comment]
There's an unadvertised `config` option: `:json_encoder`.

```
config :airbrake_config, 
   ...
  json_encoder: Jason,
  ....
```

I'm reluctant to make `Jason` the default because it'll blow up on structs that don't have encoders (where I think `Poison` just encodes them as maps).

**Comment by nacengineer** [comment]
The poison developer has woken up and released a ver 6. Closing this one. Thanks for the info.
